
### Create a new User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "passowrd": "asdfdfgh"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find a particular user iwth a given ID
GET https://localhost:3000/auth/12342134

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@adsf.com

### Delete a user given id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email" : "aaa@aaa.com"
}

### Set a color
GET http://localhost:3000/auth/colors/red

### Get the color
GET http://localhost:3000/auth/colors